using System.ComponentModel;

namespace CoinMarketCap.Enumerations
{
    public enum eInterval
    {
        [Description("yearly")]
        Yearly,
        [Description("monthly")]
        Monthly,
        [Description("weekly")]
        Weekly,
        [Description("daily")]
        Daily,
        [Description("hourly")]
        Hourly,
        [Description("5m")]
        Minutes5,
        [Description("10m")]
        Minutes10,
        [Description("15m")]
        Minutes15,
        [Description("30m")]
        Minutes30,
        [Description("45m")]
        Minutes45,
        [Description("1h")]
        Hours1,
        [Description("2h")]
        Hours2,
        [Description("3h")]
        Hours3,
        [Description("4h")]
        Hours4,
        [Description("6h")]
        Hours6,
        [Description("12h")]
        Hours12,
        [Description("24h")]
        Hours24,
        [Description("1d")]
        Days1,
        [Description("2d")]
        Days2,
        [Description("3d")]
        Days3,
        [Description("7d")]
        Days7,
        [Description("14d")]
        Days14,
        [Description("15d")]
        Days15,
        [Description("30d")]
        Days30,
        [Description("60d")]
        Days60,
        [Description("90d")]
        Days90,
        [Description("365d")]
        Days365
    }
}